import type { TransactionEvent } from '../types/events'

// Mock transaction event data - simulates real product transactions on Whop
export const mockTransactionEvents: TransactionEvent[] = [
  {
    id: 1,
    productId: 'prod_123abc',
    productSlug: 'premium-discord-bot',
    productName: 'Premium Discord Management Bot',
    description: 'Advanced Discord bot for server management and automation',
    imageUrl: 'https://example.com/discord-bot.jpg',
    seller: 'BotMasters',
    timestamp: new Date('2025-11-19T10:00:00Z'),
    rawData: { price: 49.99, currency: 'USD', category: 'discord-tools' },
  },
  {
    id: 2,
    productId: 'prod_456def',
    productSlug: 'crypto-trading-signals',
    productName: 'Crypto Trading Signals VIP',
    description: 'Premium crypto trading signals with 80% accuracy',
    imageUrl: 'https://example.com/crypto-signals.jpg',
    seller: 'CryptoGuru',
    timestamp: new Date('2025-11-19T09:30:00Z'),
    rawData: { price: 99.99, currency: 'USD', category: 'trading' },
  },
  {
    id: 3,
    productId: 'prod_789ghi',
    productSlug: 'forex-masterclass',
    productName: 'Forex Trading Masterclass 2025',
    description: 'Complete forex trading course from beginner to pro',
    imageUrl: 'https://example.com/forex-course.jpg',
    seller: 'ForexPro',
    timestamp: new Date('2025-11-19T08:15:00Z'),
    rawData: { price: 199.99, currency: 'USD', category: 'education' },
  },
  {
    id: 4,
    productId: 'prod_012jkl',
    productSlug: 'nft-alpha-group',
    productName: 'NFT Alpha Community',
    description: 'Exclusive NFT flipping strategies and early access',
    imageUrl: 'https://example.com/nft-alpha.jpg',
    seller: 'NFTKings',
    timestamp: new Date('2025-11-18T22:00:00Z'),
    rawData: { price: 149.99, currency: 'USD', category: 'nft' },
  },
  {
    id: 5,
    productId: 'prod_345mno',
    productSlug: 'copywriting-course',
    productName: 'High-Ticket Copywriting Course',
    description: 'Learn to write copy that converts and earn 6 figures',
    imageUrl: 'https://example.com/copywriting.jpg',
    seller: 'CopyKing',
    timestamp: new Date('2025-11-18T20:00:00Z'),
    rawData: { price: 297.0, currency: 'USD', category: 'marketing' },
  },
  {
    id: 6,
    productId: 'prod_678pqr',
    productSlug: 'stock-alerts-premium',
    productName: 'Stock Alerts Premium',
    description: 'Real-time stock alerts and trading recommendations',
    imageUrl: 'https://example.com/stock-alerts.jpg',
    seller: 'StockAlpha',
    timestamp: new Date('2025-11-18T18:30:00Z'),
    rawData: { price: 79.99, currency: 'USD', category: 'trading' },
  },
  {
    id: 7,
    productId: 'prod_901stu',
    productSlug: 'ecommerce-blueprint',
    productName: 'E-commerce Empire Blueprint',
    description: 'Build a profitable e-commerce business from scratch',
    imageUrl: 'https://example.com/ecommerce.jpg',
    seller: 'EcommGurus',
    timestamp: new Date('2025-11-18T16:00:00Z'),
    rawData: { price: 497.0, currency: 'USD', category: 'business' },
  },
  {
    id: 8,
    productId: 'prod_234vwx',
    productSlug: 'fitness-coaching',
    productName: 'Online Fitness Coaching Program',
    description: 'Personalized fitness coaching and meal plans',
    imageUrl: 'https://example.com/fitness.jpg',
    seller: 'FitCoach',
    timestamp: new Date('2025-11-18T14:15:00Z'),
    rawData: { price: 129.99, currency: 'USD', category: 'fitness' },
  },
  {
    id: 9,
    productId: 'prod_567yza',
    productSlug: 'dropshipping-mastery',
    productName: 'Dropshipping Mastery 2025',
    description: 'Complete dropshipping course with product research tools',
    imageUrl: 'https://example.com/dropshipping.jpg',
    seller: 'DropshipPro',
    timestamp: new Date('2025-11-17T22:30:00Z'),
    rawData: { price: 197.0, currency: 'USD', category: 'ecommerce' },
  },
  {
    id: 10,
    productId: 'prod_890bcd',
    productSlug: 'ai-automation-tools',
    productName: 'AI Automation Tools Suite',
    description: 'Powerful AI tools for business automation',
    imageUrl: 'https://example.com/ai-tools.jpg',
    seller: 'AIAutomation',
    timestamp: new Date('2025-11-17T20:00:00Z'),
    rawData: { price: 299.99, currency: 'USD', category: 'software' },
  },
]

// Top product categories
export const topCategories = [
  { name: 'Trading & Investing', count: 3 },
  { name: 'Business & Marketing', count: 2 },
  { name: 'E-commerce', count: 2 },
  { name: 'Discord Tools', count: 1 },
  { name: 'NFT & Crypto', count: 1 },
  { name: 'Fitness & Health', count: 1 },
]
